version: 0.0
os: linux
files:
  - source: build
    destination: /react
  - source: build
    destination: /react
hooks:
  BeforeInstall:
    - location: scripts/UnzipResourceBundle.sh
    # - location: Scripts/UnzipDataBundle.sh
  # AfterInstall:
  #   - location: Scripts/RunResourceTests.sh
  #     timeout: 180
  ApplicationStart:
    - location: scripts/RunFunctionalTests.sh
      timeout: 180
  # ValidateService:
  #   - location: Scripts/MonitorService.sh
  #     timeout: 180
  #     runas: root