name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - run: npm run build
    - uses: actions/checkout@v2

    - run: mkdir -p ReactBuilds/
    - run: ls
    - run: echo hello > ReactBuilds/world.txt
    - run: ls
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: /      # or path/to/artifact
